# NAME: Bach Hoang
# ID: 104737449
# EMAIL: ko.wing.bird@gmail.com

.SILENT:
files = lab3b.py lab3b Makefile README
ID = 104737449
tar_name = lab3b-$(ID).tar.gz

default: 
	chmod +x lab3b
dist:
	tar -czf $(tar_name) $(files)
clean:
